owner: iofane
repo: gitup

sites:
  - name: Crowdstrike US-1
    url: https://ts01-b.cloudsink.net
  - name: Crowdstrike Login
    url: https://falcon.crowdstrike.com/login/
  - name: Gold Coast
    url: https://www.goldcoast.qld.gov.au/Home
  - name: Netskope SV5 - 1
    check: "tcp-ping"
    url: 8.36.116.1
    port: 443
  - name: Netskope SV5 - 2
    check: "tcp-ping"
    url: cogc.goskope.com
    port: 53

status-website:
  baseUrl: /gitup
  logoUrl: https://www.icons101.com/icon_png/size_256/id_60277/258_Mudkip.png
  name: GitUp - Powered by mudkipz
  navbar:
    - title: Monitorz
      href: /
