owner: iofane
repo: gitup

sites:
  - name: Crowdstrike US-1
    url: https://ts01-b.cloudsink.net
  - name: Crowdstrike Login
    url: https://falcon.crowdstrike.com/login/
  - name: Gold Coast
    url: https://www.goldcoast.qld.gov.au/Home
  - name: Netskope SV5 MGMT IP
    icon: https://res.cloudinary.com/apideck/image/upload/v1593442136/icons/netskope.jpg
    check: "tcp-ping"
    url: 8.36.116.70
    port: 80
  - name: Netskope MGMT GW
    icon: https://res.cloudinary.com/apideck/image/upload/v1593442136/icons/netskope.jpg
    check: "tcp-ping"
    url: $NETSKOPE_GW
    port: 443
  - name: Netskope MGMT Portal
    icon: https://res.cloudinary.com/apideck/image/upload/v1593442136/icons/netskope.jpg
    url: $NETSKOPE

status-website:
  baseUrl: /gitup
  logoUrl: https://www.icons101.com/icon_png/size_256/id_60277/258_Mudkip.png
  name: GitUp - Powered by mudkipz

workflowSchedule:
  graphs: "*/5 * * * *"
  responseTime: "*/5 * * * *"
  staticSite: "*/5 * * * *"
  summary: "*/5 * * * *"
  updateTemplate: "*/5 * * * *"
  updates: "*/5 * * * *"
  uptime: "*/5 * * * *"
